import { Product, Category } from '@/types';

export const categories: Category[] = [
  { id: 'all', name: 'Tất Cả Hạt', slug: 'all', icon: 'Sparkles' },
  { id: 'premium-nuts', name: 'Hạt Nhập Khẩu & Đặc Sản', slug: 'hat-nhap-khau-dac-san', icon: 'Nut', itemCount: 16 },
  { id: 'granola-cereal', name: 'Granola Siêu Hạt & KETO', slug: 'granola-sieu-hat-keto', icon: 'Cookie', itemCount: 12 },
  { id: 'nut-butter-milk', name: 'Bơ Hạt & Sữa Hạt Tươi', slug: 'bo-hat-sua-hat-tuoi', icon: 'CupSoda', itemCount: 8 },
  { id: 'raw-seeds', name: 'Hạt Nấu Sữa & Làm Bánh', slug: 'hat-nau-sua-lam-banh', icon: 'Wheat', itemCount: 10 },
  { id: 'daily-pack', name: 'Combo Hạt Chia Sẵn Theo Ngày', slug: 'combo-hat-chia-san', icon: 'CalendarDays', itemCount: 6 },
];

export const mockProducts: Product[] = [
  {
    id: 'nut-1',
    name: 'Hạt Macca Nứt Vỏ Tây Nguyên Sấy Nứt Tự Nhiên',
    slug: 'hat-macca-nut-vo-tay-nguyen',
    price: 145000,
    originalPrice: 175000,
    unit: 'hũ 500g (kèm dụng cụ tách)',
    thumbnail: 'https://images.unsplash.com/photo-1536591375315-1b83681577a7?auto=format&fit=crop&w=600&q=80',
    category: categories[1],
    categoryId: 'premium-nuts',
    servingSize: '30g (10-12 hạt)',
    calories: 215,
    protein: 2.5,
    carbs: 4.2,
    fat: 23,
    fiber: 2.6,
    sugar: 1.3,
    nutriScore: 'A',
    badges: ['ORGANIC', 'VIETGAP', 'KETO'],
    allergens: ['PEANUTS'],
    rating: 5.0,
    reviewCount: 328,
    isAvailable: true,
    stock: 45,
    farmOrigin: 'Nông trường Macca Krông Năng, Đắk Lắk',
    description: 'Hạt macca tươi tuyển chọn loại VIP, sấy nứt nhiệt độ thấp giữ nguyên 100% dầu béo tự nhiên, giàu Omega-7 và vitamin E tốt cho tim mạch và mẹ bầu.',
  },
  {
    id: 'nut-2',
    name: 'Hạnh Nhân Mỹ Rang Mộc Không Muối (Organic Raw)',
    slug: 'hanh-nhan-my-rang-moc',
    price: 130000,
    originalPrice: 155000,
    unit: 'hũ 500g',
    thumbnail: 'https://images.unsplash.com/photo-1508061252966-f72fb98cbc60?auto=format&fit=crop&w=600&q=80',
    category: categories[1],
    categoryId: 'premium-nuts',
    servingSize: '30g (~23 hạt)',
    calories: 172,
    protein: 6.2,
    carbs: 6.1,
    fat: 14.8,
    fiber: 3.5,
    sugar: 1.2,
    nutriScore: 'A',
    badges: ['ORGANIC', 'HIGH_PROTEIN', 'LOW_SUGAR'],
    allergens: ['PEANUTS'],
    rating: 4.9,
    reviewCount: 245,
    isAvailable: true,
    stock: 60,
    farmOrigin: 'California Farms, Hoa Kỳ (USDA Organic)',
    description: 'Hạnh nhân chuẩn giống Nonpareil thơm bùi giòn rụm, sấy mộc 100% không thêm muối hay gia vị, nguồn vitamin E và magiê dồi dào hỗ trợ giảm cholesterol.',
  },
  {
    id: 'nut-3',
    name: 'Granola Siêu Hạt Vị Chocolate Đen & Dừa Nướng',
    slug: 'granola-sieu-hat-chocolate-den',
    price: 155000,
    originalPrice: 185000,
    unit: 'hũ 500g',
    thumbnail: 'https://images.unsplash.com/photo-1517093157656-b9ec816538b8?auto=format&fit=crop&w=600&q=80',
    category: categories[2],
    categoryId: 'granola-cereal',
    servingSize: '40g / khẩu phần',
    calories: 188,
    protein: 7.8,
    carbs: 16.5,
    fat: 9.4,
    fiber: 4.2,
    sugar: 3.5,
    nutriScore: 'A',
    badges: ['ORGANIC', 'LOW_SUGAR', 'KETO'],
    allergens: ['PEANUTS', 'GLUTEN'],
    rating: 4.9,
    reviewCount: 412,
    isAvailable: true,
    stock: 35,
    farmOrigin: 'Chế biến từ 85% hạt dinh dưỡng & bột cacao nguyên chất',
    description: '85% Macca, Hạnh nhân, Hạt điều, Yến mạch nướng mật ong hoa nhãn kết hợp bột cacao nguyên chất đắng nhẹ thanh mát, thích hợp ăn cùng sữa chua Hy Lạp.',
  },
  {
    id: 'nut-4',
    name: 'Hạt Điều Bình Phước Rang Củi Nguyên Lụa Loại 1',
    slug: 'hat-dieu-binh-phuoc-rang-cui',
    price: 125000,
    originalPrice: 145000,
    unit: 'hộp 500g',
    thumbnail: 'https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?auto=format&fit=crop&w=600&q=80',
    category: categories[1],
    categoryId: 'premium-nuts',
    servingSize: '30g (16-18 hạt)',
    calories: 165,
    protein: 5.5,
    carbs: 9.2,
    fat: 13.1,
    fiber: 1.0,
    sugar: 1.7,
    nutriScore: 'A',
    badges: ['VIETGAP', 'NON_GMO'],
    allergens: ['PEANUTS'],
    rating: 4.9,
    reviewCount: 198,
    isAvailable: true,
    stock: 50,
    farmOrigin: 'Vùng nguyên liệu Hạt điều Bù Đăng, Bình Phước',
    description: 'Hạt điều cùi to mẩy tròn size A+, rang củi thủ công giữ trọn độ ngậy béo, chỉ chà nhẹ là bong lớp vỏ lụa, không hôi dầu.',
  },
  {
    id: 'nut-5',
    name: 'Bơ Hạt Điều Hữu Cơ 100% Thuần Khiết Không Đường',
    slug: 'bo-hat-dieu-huu-co-khong-duong',
    price: 95000,
    originalPrice: 115000,
    unit: 'hũ thủy tinh 300g',
    thumbnail: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=600&q=80',
    category: categories[3],
    categoryId: 'nut-butter-milk',
    servingSize: '25g (2 muỗng)',
    calories: 148,
    protein: 4.8,
    carbs: 7.2,
    fat: 12.3,
    fiber: 1.2,
    sugar: 1.5,
    nutriScore: 'A',
    badges: ['VEGAN', 'KETO', 'LOW_SUGAR'],
    allergens: ['PEANUTS'],
    rating: 4.8,
    reviewCount: 88,
    isAvailable: true,
    stock: 25,
    farmOrigin: 'Sản xuất tại nhà xưởng đạt chuẩn HACCP',
    description: 'Bơ hạt điều mịn sánh mịn màng, làm 100% từ hạt điều tươi nghiền cối đá, không hydro hóa, không đường tinh luyện, bổ sung chất béo lành mạnh mỗi sáng.',
  },
  {
    id: 'nut-6',
    name: 'Hạt Óc Chó Vàng Chandler Mỹ Tách Vỏ Sẵn (Extra Light)',
    slug: 'hat-oc-cho-chandler-my-tach-vo',
    price: 165000,
    originalPrice: 195000,
    unit: 'hũ 500g',
    thumbnail: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80',
    category: categories[1],
    categoryId: 'premium-nuts',
    servingSize: '30g (~7 quả)',
    calories: 196,
    protein: 4.6,
    carbs: 4.1,
    fat: 19.5,
    fiber: 2.0,
    sugar: 0.8,
    nutriScore: 'A',
    badges: ['ORGANIC', 'NON_GMO', 'KETO'],
    allergens: ['PEANUTS'],
    rating: 4.9,
    reviewCount: 164,
    isAvailable: true,
    stock: 30,
    farmOrigin: 'Vườn óc chó Chandler, Northern California',
    description: 'Hạt óc chó giàu hàm lượng Axit béo Omega-3 Alpha-Linolenic (ALA) nhất trong các loại hạt, hỗ trợ phát triển trí não cho bé và duy trì huyết áp ổn định.',
  },
  {
    id: 'nut-7',
    name: 'Hạt Bí Xanh Ấn Độ Sấy Mộc Chuẩn Organic',
    slug: 'hat-bi-xanh-an-do-say-moc',
    price: 85000,
    originalPrice: 105000,
    unit: 'hũ 500g',
    thumbnail: 'https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&w=600&q=80',
    category: categories[4],
    categoryId: 'raw-seeds',
    servingSize: '30g (khoảng 3 muỗng canh)',
    calories: 168,
    protein: 9.0,
    carbs: 4.5,
    fat: 13.8,
    fiber: 2.2,
    sugar: 0.4,
    nutriScore: 'A',
    badges: ['ORGANIC', 'HIGH_PROTEIN', 'VEGAN'],
    allergens: [],
    rating: 4.8,
    reviewCount: 122,
    isAvailable: true,
    stock: 40,
    farmOrigin: 'Nông trại canh tác hữu cơ Rajasthan, Ấn Độ',
    description: 'Hạt bí xanh hạt to đều tăm tắp, giàu Kẽm và Magiê thực vật giúp cải thiện chất lượng giấc ngủ, tăng cường hệ miễn dịch và hỗ trợ tuyến tiền liệt.',
  },
  {
    id: 'nut-8',
    name: 'Gói Hạt Daily Mix 7 Ngày (Định Lượng 30g/Túi)',
    slug: 'goi-hat-daily-mix-7-ngay',
    price: 175000,
    originalPrice: 210000,
    unit: 'hộp 7 gói nhỏ x 30g',
    thumbnail: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    category: categories[5],
    categoryId: 'daily-pack',
    servingSize: '1 gói nhỏ (30g)',
    calories: 175,
    protein: 5.5,
    carbs: 8.0,
    fat: 14.2,
    fiber: 3.0,
    sugar: 2.5,
    nutriScore: 'A',
    badges: ['ORGANIC', 'KETO', 'VIETGAP'],
    allergens: ['PEANUTS'],
    rating: 5.0,
    reviewCount: 512,
    isAvailable: true,
    stock: 70,
    farmOrigin: 'Tổng hợp từ các nông trường kiểm định đạt chuẩn ISO 22000',
    description: 'Giải pháp ăn vặt thông minh: Mỗi ngày 1 túi nhỏ mix đều 5 loại hạt (Macca, Hạnh nhân, Óc chó, Hạt điều, Nho khô đen) chuẩn 175 kcal, mang đi làm đi học cực tiện.',
  },
];
